import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Bloggerrr",
  description: "Generated by create next app",
};

let header =(
  <header className="text-3xl m-4 p-4 font-bold text-slate-800 hover:text-sky-700 bg-gray-100">
  <Link href={'/'}>
  <h1>Bloggeerr</h1>
  </Link>
  </header>
)

let footer = (
  <footer className="p-4 border-t border-gray-200 flex justify-center items-center">
   <p className="text-sm text-gray-600">
     &copy; 2024
    </p>
  </footer>
)

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {header}
        {children}
        {footer}
        </body>
    </html>
  );
}
